### ISSUE TITLE
The github version is not working as the online version

### ISSUE THREAD

**Issue by Amandeepsinghghai** [spite/polygon-shredder#2]
Hey. First of all, this is an amazing project and has given me a lot of knowledge regarding three.js.

Wrt the issue, I was wondering the lights are a bit off compared to the [online version](https://www.clicktorelease.com/code/polygon-shredder/). Is there something that I am missing here?

**Comment by spite** [comment]
No, i don't think so. Are you running the project with a file server so the spotlight texture loads without throwing an origin error?

**Comment by seecee96** [comment]
Hey, same issue and yes there is no error, although it does take a bit longer to load than the online version.

**Comment by spite** [comment]
Could you provide some explanation of what you think is different?

**Comment by christiankaseburg** [comment]
This is a reply to a old post, but if other people are having problems with this still I uploaded the spotlight.jpg to my file server. In the main-boxels.js you just need to search for the texLoader.load, and change the url path from spotlight to https://s3.us-east-2.amazonaws.com/christiankaseburgbucket/spotlight.jpg. This is just an alternate fix.

**Comment by spite** [comment]
I don't know what issues you are all having with images, but they're correctly submitted in the repo. I've made the repo, as it is, public on github pages http://spite.github.io/polygon-shredder/ and it works. You'll have to figure out how your server is serving files.
