### ISSUE TITLE
CurlNoise function

### ISSUE THREAD

**Issue by taseenb** [spite/polygon-shredder#3]
I would like to use the CurlNoise function and was wondering who's the author (to mention her/him). Is that you @spite or someone else? I'm talking about this one:

```
vec3 curlNoise( vec3 p ){
	const float e = .1;
	vec3 dx = vec3( e   , 0.0 , 0.0 );
	vec3 dy = vec3( 0.0 , e   , 0.0 );
	vec3 dz = vec3( 0.0 , 0.0 , e   );
	vec3 p_x0 = snoiseVec3( p - dx );
	vec3 p_x1 = snoiseVec3( p + dx );
	vec3 p_y0 = snoiseVec3( p - dy );
	vec3 p_y1 = snoiseVec3( p + dy );
	vec3 p_z0 = snoiseVec3( p - dz );
	vec3 p_z1 = snoiseVec3( p + dz );
	float x = p_y1.z - p_y0.z - p_z1.y + p_z0.y;
	float y = p_z1.x - p_z0.x - p_x1.z + p_x0.z;
	float z = p_x1.y - p_x0.y - p_y1.x + p_y0.x;
	const float divisor = 1.0 / ( 2.0 * e );
	return normalize( vec3( x , y , z ) * divisor );
}
```

By the way I also noticed that 2 other curl noise and 1 noise functions are not even used! You could remove ~100 lines. Amazing how short and clean is the code, compared to the complexity of the result. Bravo :)

**Comment by spite** [comment]
Curl noise is a fairly standard way of getting divergence free fields. There's many GLSL implementations out there. Differences in the implementation yield different results in the simulation. Here's some examples:

https://github.com/dli/flow
https://github.com/cabbibo/glsl-curl-noise
https://codepen.io/timseverien/pen/EmJNOR

In this case i'm using cabbibo's, but i don't remember where he got it from.

**Comment by taseenb** [comment]
Thanks @spite
