### ISSUE TITLE
Non-interactive version?

### ISSUE THREAD

**Issue by iangilman** [spite/polygon-shredder#4]
I'm in the process of building a community for celebrating code-based art:

http://www.artywidget.com/
http://www.artywidget.com/about/

… and I'd love to include The Polygon Shredder. The focus for that site is passive art; think of a TV or photo frame on the wall where there may not even be an option for interaction. For that reason, I'd love to be able to programmatically hit the "close controls" and "close this message" buttons (e.g. with a URL parameter) so the audience can kick back and enjoy the art without extra visual distraction. Would that be okay with you? I'm happy to make a patch to this effect, but I wanted to check with you first.

**Comment by spite** [comment]
Yes, absolutely: adding #frame.{size} to the URL will create a {size}x{size} polygon shredder without HUD or UI. Here's the code that handles that: https://github.com/spite/polygon-shredder/blob/master/js/main-boxels.js#L44

Size has to be a number between 1 and something like 2048 or 4096, depending on the hardware, ideally a power of two. The polygon shredder runs by default at 256.

For example: https://www.clicktorelease.com/code/polygon-shredder/#frame.512

Let me know if that helps!

**Comment by iangilman** [comment]
Wow, yes, that's exactly what I was hoping for! Beautiful :-)

… And here it is on the site:

http://www.artywidget.com/artwork/59c49dc4c383e88db9eb5820/

Thank you!
