### ISSUE TITLE
Black screen when clicking Enter VR.

### ISSUE THREAD

**Issue by ngokevin** [spite/polygon-shredder#7]
On Firefox Developer Edition with HTC Vive: https://www.clicktorelease.com/code/polygon-shredder/vr/

On desktop mirror, it tracks the headset pose, but the screen and headset are black after clicking Enter VR.

**Comment by spite** [comment]
Yeah... it hasn't been updated in ages. Some day!

**Comment by dmarcos** [comment]
@spite Fixed here for you when you have time https://github.com/dmarcos/polygon-shredder/tree/webvr
